routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');



//Rota para alterar o dados do usuário
/* Route::get('/model', function(){
$user = App\User::find(1);
$user->name = 'Admin';
$user->email = 'admin@example.com';
$user->password = bcrypt('admin');
$user->save();
}); */

//Rota para listar todos os produtos
/* Route::get('/model', function(){
    $products = App\Product::all();

    return $products;
    
    });*/

//Rota para listar todos os produtos
/* Route::get('/model', function(){
    
    return App\User::all();
}); */

//Rota para listar todos os usuários paginados
/* Route::get('/model', function(){
    return \App\User::paginate(10);
}); */

/* Route::get('/model', function(){
    $user = App\User::find(4);
    return $user->store;
    return \App\User::all();
}); */

//Rota normal
/* Route::get('/admin/stores', 'Admin\\StoreController@index');
Route::get('/admin/stores/create', 'Admin\\StoreController@create');
Route::post('/admin/stores/store', 'Admin\\StoreController@store'); */


Route::group(['middleware' => ['auth']], function () 
{
    //Rotas simplificadas
    Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function () {

        /* Route::prefix('/stores')->name('stores.')->group(function () 
        {
            Route::get('/', 'StoreController@index')->name('index');
            Route::get('/create', 'StoreController@create')->name('create');
            Route::post('/store', 'StoreController@store')->name('store');
            Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
            Route::post('/update/{store}', 'StoreController@update')->name('update');
            Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
        }); */
        
        Route::resource('stores', 'StoreController');
        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');

        Route::post('photos/remove', 'ProductPhotoController@removePhoto')->name('photo.remove');

    });    
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    protected $fillable = ['name', 'description', 'phone', 'mobile_phone', 'slug', 'logo'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/Admin/StoreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\flash;
use App\Http\Requests\StoreRequest;
use App\Traits\UploadTrait;
use Illuminate\Support\Facades\Storage;

class StoreController extends Controller
{
    use UploadTrait;

    /* Função construtor criada para chamar o Middleware criado, apenas para create e store */
    public function __construct()
    {
        $this->middleware('user.has.store')->only(['create', 'store']);
    }

    public function index()
    {
        $store = auth()->user()->store;

        return view('admin.stores.index', compact('store'));
    }

    public function create()
    {

        $users = \App\User::all(['id', 'name']);

        return view('admin.stores.create', compact('users'));
    }

    public function store(StoreRequest $request)
    {
        $data = $request->all();

        $user = auth()->user();

        if($request->hasFile('logo')){
            $data['logo'] = $this->imageUpload($request->file('logo'));
        }
        
        $store = $user->store()->create($data);

        flash('Loja criada com sucesso!')->success();
        return redirect ()->route('admin.stores.create');
    }

    public function edit($store)
    {
        $store = \App\Store::find($store);

        return view('admin.stores.edit', compact('store'));
    }

    public function update(StoreRequest $request, $store)
    {
        $data = $request->all();
        $store = \App\Store::find($store);

        if($request->hasFile('logo')){
            if(Storage::disk('public')->exists($store->logo)){
                Storage::disk('public')->delete($store->logo);
            }
            $data['logo'] = $this->imageUpload($request->file('logo'));
        }

        
        $store->update($data);

        flash('Loja atualizada com sucesso!')->success();
        return redirect()->route("admin.stores.index");
    }

    public function destroy($store)
    {
        $store = \App\Store::find($store);
        $store->delete();

        flash('Loja excluída com sucesso!')->success();
        return redirect('/admin/stores');
    }

}

resources/views/admin/stores/create.blade.php
@extends('layouts.app')
@section('content')
    <h1>Criar loja</h1>
    <form action="{{ route('admin.stores.store') }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label>Nome Loja</label>
            <!-- Identifica o erro e retorna na tela para o usuário no imput -->
            <!-- old retorna no input o ultimo texto digitado pelo usuário -->
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">            
            @error('name') <!-- Identifica o erro e retorna na tela para o usuário -->
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description')}}">
            @error('description')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Telefone</label>
            <input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{old('phone')}}">
            @error('phone')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Celular/Whatsapp</label>
            <input type="text" name="mobile_phone" class="form-control @error('mobile_phone') is-invalid @enderror" value="{{old('mobile_phone')}}">
            @error('mobile_phone')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="">Logo da loja</label>
            <input type="file" name="logo" class="form-control @error('logo') is-invalid @enderror" value="">
            @error('logo')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control">
        </div>                
        <div>
            <button type="submit" class="btn btn-lg btn-success mt-3">Criar loja</button>
            <a href="{{ route('admin.stores.index') }}" class="btn btn-lg btn-secondary mt-3">Voltar</a>
        </div>        
    </form>
@endsection

resources/views/admin/stores/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1>Editar loja</h1>
    <form action="{{ route('admin.stores.update', ['store'=>$store->id]) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label>Nome Loja</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ $store->name }}">
            @error('name')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{ $store->description }}">
            @error('description')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Telefone</label>
            <input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ $store->phone }}">
            @error('phone')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Celular/Whatsapp</label>
            <input type="text" name="mobile_phone" class="form-control @error('mobile_phone') is-invalid @enderror" value="{{ $store->mobile_phone }}">
            @error('mobile_phone')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <p>
                <img src="{{asset('storage/' . $store->logo)}}" alt="">
            </p>
            <label for="">Logo da loja</label>
            <input type="file" name="logo" class="form-control @error('logo') is-invalid @enderror" value="">
            @error('logo')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control" value="{{ $store->slug }}">
        </div>  
        <div>
            <button type="submit" class="btn btn-lg btn-success mt-3">Atualizar loja</button>
            <a href="{{ route('admin.stores.index') }}" class="btn btn-lg btn-secondary mt-3">Voltar</a>
        </div>
    </form>
@endsection

resources/views/admin/stores/index.blade.php
@extends('layouts.app')
@section('content')

<!-- Para fazer o botão de criar loja só aparecer se o usuário não possuir loja -->
@if(!$store)
    <a href="{{ route('admin.stores.create') }}" class="btn btn-lg btn-success mt-3">Criar loja</a>
@else
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome da loja</th>
            <th>Total de produtos</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>        
        <tr>
            <td>{{ $store->id  }}</td>
            <td>{{ $store->name }}</td>
            <td>{{ $store->products->count()}}</td>
            <td>
                <div class="btn-group">
                    <a href="{{ route('admin.stores.edit', ['store'=>$store->id]) }}" class="btn btn-sm btn-primary" title="Editar"><i class="bi bi-pencil-square"></i></a>
                    <form action="{{ route('admin.stores.destroy', ['store'=>$store->id]) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-danger" title="Excluir"><i class="bi bi-trash3-fill"></i></button>
                    </form>
                </div>
            </td>
        </tr>        
    </tbody>
</table>
@endif
@endsection