routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');



//Rota para alterar o dados do usuário
/* Route::get('/model', function(){
$user = App\User::find(1);
$user->name = 'Admin';
$user->email = 'admin@example.com';
$user->password = bcrypt('admin');
$user->save();
}); */

//Rota para listar todos os produtos
/* Route::get('/model', function(){
    $products = App\Product::all();

    return $products;
    
    });*/

//Rota para listar todos os produtos
/* Route::get('/model', function(){
    
    return App\User::all();
}); */

//Rota para listar todos os usuários paginados
/* Route::get('/model', function(){
    return \App\User::paginate(10);
}); */

/* Route::get('/model', function(){
    $user = App\User::find(4);
    return $user->store;
    return \App\User::all();
}); */

//Rota normal
/* Route::get('/admin/stores', 'Admin\\StoreController@index');
Route::get('/admin/stores/create', 'Admin\\StoreController@create');
Route::post('/admin/stores/store', 'Admin\\StoreController@store'); */


Route::group(['middleware' => ['auth']], function () 
{
    //Rotas simplificadas
    Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function () {

        /* Route::prefix('/stores')->name('stores.')->group(function () 
        {
            Route::get('/', 'StoreController@index')->name('index');
            Route::get('/create', 'StoreController@create')->name('create');
            Route::post('/store', 'StoreController@store')->name('store');
            Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
            Route::post('/update/{store}', 'StoreController@update')->name('update');
            Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
        }); */
        
        Route::resource('stores', 'StoreController');
        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');

        Route::post('photos/remove', 'ProductPhotoController@removePhoto')->name('photo.remove');

    });    
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>Marktplace L6</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet">
    <!-- CSN para adiconar estilização do bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- CDN para adiconar icones ao site -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>

<body>
    <!-- Adcionando o navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark" style="margin-bottom: 40px;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{route('home')}}">Marketplace L6</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                @auth <!--só exibe o conteúdo se o usuário estiver logado -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link @if(request()->is('admin/stores*')) active @endif" aria-current="page" href="{{ route('admin.stores.index') }}">Lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @if(request()->is('admin/products*')) active @endif" href="{{ route('admin.products.index') }}">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @if(request()->is('admin/categories*')) active @endif" href="{{ route('admin.categories.index') }}">Categorias</a>
                        </li>                    
                    </ul>
                    <div class="my-2 my-lg-0">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="#" onclick="event.preventDefault(); document.querySelector('form.logout').submit(); ">Sair</a>
                                <form action="{{route('logout')}}" class="logout" method="POST" style="display:none;">
                                    @csrf
                                </form>
                            </li>
                            <li>
                                <span class="nav-link">{{auth()->user()->name}}</span>
                            </li>
                        </ul>
                    </div>
                @endauth                
            </div>
        </div>
    </nav>
    <div class="container">
        @include('flash::message')
        @yield('content')
    </div>
</body>
</html>