routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');



//Rota para alterar o dados do usuário
/* Route::get('/model', function(){
$user = App\User::find(1);
$user->name = 'Admin';
$user->email = 'admin@example.com';
$user->password = bcrypt('admin');
$user->save();
}); */

//Rota para listar todos os produtos
/* Route::get('/model', function(){
    $products = App\Product::all();

    return $products;
    
    });*/

//Rota para listar todos os produtos
/* Route::get('/model', function(){
    
    return App\User::all();
}); */

//Rota para listar todos os usuários paginados
/* Route::get('/model', function(){
    return \App\User::paginate(10);
}); */

/* Route::get('/model', function(){
    $user = App\User::find(4);
    return $user->store;
    return \App\User::all();
}); */

//Rota normal
/* Route::get('/admin/stores', 'Admin\\StoreController@index');
Route::get('/admin/stores/create', 'Admin\\StoreController@create');
Route::post('/admin/stores/store', 'Admin\\StoreController@store'); */


Route::group(['middleware' => ['auth']], function () 
{
    //Rotas simplificadas
    Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function () {

        /* Route::prefix('/stores')->name('stores.')->group(function () 
        {
            Route::get('/', 'StoreController@index')->name('index');
            Route::get('/create', 'StoreController@create')->name('create');
            Route::post('/store', 'StoreController@store')->name('store');
            Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
            Route::post('/update/{store}', 'StoreController@update')->name('update');
            Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
        }); */
        
        Route::resource('stores', 'StoreController');
        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');

        Route::post('photos/remove', 'ProductPhotoController@removePhoto')->name('photo.remove');

    });    
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{   
    protected $fillable = [
        'name', 'description', 'slug'
    ];
    
    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Store;
use App\Category;
use Illuminate\Support\Facades\Flash;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{

    private $category;

    public function __construct(Category $category)
    {
        $this->category = $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->category->paginate(10);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /* $users = \App\User::all(['id', 'name']);

        return view('admin.categories.create', compact('users')); */
        
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   

     public function store(CategoryRequest $request)
    {
        $data = $request->all();

        $category = $this->category->create($data);

        flash('Categoria criada com sucesso!')->success();

        return redirect()->route('admin.categories.index');

        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($category)
    {
        $category = $this->category->findOrFail($category);
        return view('admin.categories.edit', compact('category'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $category)
    {
        $data = $request->all();

        $category = $this->category->find($category);

        $category->update($data);

        flash('Categoria atualizada com sucesso')->success();

        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($category)
    {
        $category = $this->category->find($category);

        $category->delete();

        flash('Categoria excluida com sucesso')->success();

        return redirect()->route('admin.categories.index');
    
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <h1>Criar categoria</h1>
    <form action="{{ route('admin.categories.store') }}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label>Nome da categoria</label>
            <!-- Identifica o erro e retorna na tela para o usuário no imput -->
            <!-- old retorna no input o ultimo texto digitado pelo usuário -->
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">            
            @error('name') <!-- Identifica o erro e retorna na tela para o usuário -->
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description')}}">
            @error('description')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>        
        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control">
        </div>                
        <div>
            <button type="submit" class="btn btn-lg btn-success mt-3">Criar categoria</button>
            <a href="{{ route('admin.categories.index') }}" class="btn btn-lg btn-secondary mt-3">Voltar</a>
        </div>        
    </form>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1>Editar categoria</h1>
    <form action="{{ route('admin.categories.update', ['category'=>$category->id]) }}" method="post">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label>Nome</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ $category->name }}">
            @error('name')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{ $category->description }}">
            @error('description')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>       
        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control" value="{{ $category->slug }}">
        </div>  
        <div>
            <button type="submit" class="btn btn-lg btn-success mt-3">Atualizar categoria</button>
            <a href="{{ route('admin.categories.index') }}" class="btn btn-lg btn-secondary mt-3">Voltar</a>
        </div>
    </form>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')
@section('content')

<a href="{{ route('admin.categories.create') }}" class="btn btn-lg btn-success mt-3">Criar Categoria</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>            
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)        
            <tr>
                <td>{{ $category->id  }}</td>
                <td>{{ $category->name }}</td>            
                <td>
                    <div class="btn-group">
                        <a href="{{ route('admin.categories.edit', ['category'=>$category->id]) }}" class="btn btn-sm btn-primary" title="Editar"><i class="bi bi-pencil-square"></i></a>
                        <form action="{{ route('admin.categories.destroy', ['category'=>$category->id]) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" title="Excluir"><i class="bi bi-trash3-fill"></i></button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach        
    </tbody>
</table>

{{ $categories->links() }}

@endsection